version: 2
updates:
- package-ecosystem: mix
  directory: "/backend"
  schedule:
    interval: monthly
    time: "07:07"
    timezone: US/Central
  open-pull-requests-limit: 10
  assignees:
  - mreishus
  ignore:
  - dependency-name: swoosh
    versions:
    - 1.1.2
    - 1.3.0
  - dependency-name: phoenix
    versions:
    - 1.5.7
  - dependency-name: parent
    versions:
    - 0.11.2
  - dependency-name: postgrex
    versions:
    - 0.15.7
  - dependency-name: pow
    versions:
    - 1.0.21
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: monthly
    time: "07:07"
    timezone: US/Central
  open-pull-requests-limit: 10
  assignees:
  - mreishus
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: react-icons
    versions:
    - 4.1.0
  - dependency-name: react-scroll-to-bottom
    versions:
    - 4.0.0
  - dependency-name: date-fns
    versions:
    - 2.16.1
- package-ecosystem: docker
  directory: "/backend"
  schedule:
    interval: monthly
    time: "07:07"
    timezone: US/Central
  open-pull-requests-limit: 10
  assignees:
  - mreishus
  ignore:
  - dependency-name: alpine
    versions:
    - 3.12.3
    - 3.13.1
  - dependency-name: elixir
    versions:
    - 1.11.2.pre.alpine
- package-ecosystem: docker
  directory: "/frontend"
  schedule:
    interval: monthly
    time: "07:07"
    timezone: US/Central
  open-pull-requests-limit: 10
  assignees:
  - mreishus
  ignore:
  - dependency-name: nginx
    versions:
    - 1.19.6.pre.alpine
